### ISSUE TITLE
Calling RAG_LLM

### ISSUE THREAD

**Issue by heungh** [aws-solutions-library-samples/guidance-for-dynamic-game-npc-dialogue-on-aws#1]
Hi team, I built and run this demo succesfully.
But I got crash error when calling RAG_LLM. I checked the cloudformation stack's status as completed.
I attached ue log about the error. 
[error.log](https://github.com/aws-solutions-library-samples/guidance-for-dynamic-game-npc-dialogue-on-aws/files/14490688/error.log)
![crash_error_of_ue47](https://github.com/aws-solutions-library-samples/guidance-for-dynamic-game-npc-dialogue-on-aws/assets/82863575/dd9f779b-44bc-4d63-8d53-938ad85d9e7d)

And here is the error message I captured when I got crash error.
LoginId:f2015bd742d1d4ddb8fc8aa59042b86a
EpicAccountId:0b71d4438b924ea4afbe8586e487f747

Assertion failed: IsValid() [File:Runtime\Core\Public\Templates/SharedPointer.h] [Line: 890]

AmazonPollyMetaHuman!FDebug::AssertFailed()
AmazonPollyMetaHuman!FDebug::CheckVerifyFailedImpl()
AmazonPollyMetaHuman!USpeechComponent::OnResponseReceived() [G:\AmazonPollyMetaHuman\Source\AmazonPollyMetaHuman\Private\SpeechComponent.cpp:90]
AmazonPollyMetaHuman!TBaseUObjectMethodDelegateInstance<0,USpeechComponent,void __cdecl(TSharedPtr<IHttpRequest,1>,TSharedPtr<IHttpResponse,1>,bool),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [D:\Epic Games\UE_4.27\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:611]
AmazonPollyMetaHuman!TDelegate<void __cdecl(TSharedPtr<IHttpRequest,1>,TSharedPtr<IHttpResponse,1>,bool),FDefaultDelegateUserPolicy>::ExecuteIfBound<void,0>()
AmazonPollyMetaHuman!FCurlHttpRequest::FinishedRequest()
AmazonPollyMetaHuman!FHttpManager::Tick()
AmazonPollyMetaHuman!FTicker::Tick()
AmazonPollyMetaHuman!TStringView<wchar_t>::operator[]()
AmazonPollyMetaHuman!?Execute@?$TBaseFunctorDelegateInstance@$$A6A_NM@ZUFDefaultDelegateUserPolicy@@V?$TFunction@$$A6A_NM@Z@@$$V@@UEBA_NM@Z()
AmazonPollyMetaHuman!FTicker::Tick()
AmazonPollyMetaHuman!FEngineLoop::Tick()
AmazonPollyMetaHuman!GuardedMain()
AmazonPollyMetaHuman!GuardedMainWrapper()
AmazonPollyMetaHuman!LaunchWindowsStartup()
AmazonPollyMetaHuman!WinMain()
AmazonPollyMetaHuman!__scrt_common_main_seh() [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by heungh** [comment]
I think that this may be the reason below:  

[2024.03.05-05.04.39:577][927]LogHttp: Warning: 0000027E0F127200: libcurl info message cache 0 (Protocol " https" not supported or disabled in libcurl)

Here is the part of log what the error is from :
[2024.03.05-05.04.39:546][925]LogPollyMsg: Display: Rag LLM
[2024.03.05-05.04.39:546][925]LogPollyMsg: Display: If Else
[2024.03.05-05.04.39:546][925]LogPollyMsg: Display: Request sent to API Gateway
[2024.03.05-05.04.39:577][927]LogHttp: Warning: 0000027E0F127200: request failed, libcurl error: 1 (Unsupported protocol)
[2024.03.05-05.04.39:577][927]LogHttp: Warning: 0000027E0F127200: libcurl info message cache 0 (Protocol " https" not supported or disabled in libcurl)
[2024.03.05-05.04.39:577][927]LogHttp: Warning: 0000027E0F127200: libcurl info message cache 1 (Closing connection -1)
[2024.03.05-05.04.39:578][927]LogPollyMsg: Display: Response Received
[2024.03.05-05.04.39:578][927]LogTemp: Display: Response 
[2024.03.05-05.04.39:578][927]LogOutputDevice: Warning:

**Comment by heungh** [comment]
And I found this error is from Lambda with QA APIGW(RAG_LLM) below:
On the cloudwatch log of the lambda, there is the error below! I think the lambda code should be modified 
[ERROR] TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "/var/task/aws_lambda_powertools/tracing/tracer.py", line 313, in decorate
    response = lambda_handler(event, context, **kwargs)
  File "/var/task/index.py", line 31, in lambda_handler
    body = json.loads(event["body"])
  File "/var/lang/lib/python3.12/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '

**Comment by heungh** [comment]
{
    "level": "INFO",
    "location": "lambda_handler:30",
    "message": "Received event: {\n  \"resource\": \"/\",\n  \"path\": \"/\",\n  \"httpMethod\": \"GET\",\n  \"headers\": {\n    \"Accept\": \"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7\",\n    \"Accept-Encoding\": \"gzip, deflate, br\",\n    \"Accept-Language\": \"ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7\",\n    \"CloudFront-Forwarded-Proto\": \"https\",\n    \"CloudFront-Is-Desktop-Viewer\": \"true\",\n    \"CloudFront-Is-Mobile-Viewer\": \"false\",\n    \"CloudFront-Is-SmartTV-Viewer\": \"false\",\n    \"CloudFront-Is-Tablet-Viewer\": \"false\",\n    \"CloudFront-Viewer-ASN\": \"9318\",\n    \"CloudFront-Viewer-Country\": \"KR\",\n    \"dnt\": \"1\",\n    \"Host\": \"XXXXXXXX.execute-api.us-east-1.amazonaws.com\",\n    \"Referer\": \"https://us-east-1.console.aws.amazon.com/\",\n    \"sec-ch-ua\": \"\\\"Not A(Brand\\\";v=\\\"99\\\", \\\"Google Chrome\\\";v=\\\"121\\\", \\\"Chromium\\\";v=\\\"121\\\"\",\n    \"sec-ch-ua-mobile\": \"?0\",\n    \"sec-ch-ua-platform\": \"\\\"macOS\\\"\",\n    \"sec-fetch-dest\": \"document\",\n    \"sec-fetch-mode\": \"navigate\",\n    \"sec-fetch-site\": \"cross-site\",\n    \"sec-fetch-user\": \"?1\",\n    \"upgrade-insecure-requests\": \"1\",\n    \"User-Agent\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36\",\n    \"Via\": \"2.0 0af2958fb50cf89ab08e237abcd39288.cloudfront.net (CloudFront)\",\n    \"X-Amz-Cf-Id\": \"XxQjwGz8_fDGJWCT3svzcD5Vfnh3Jjz3kYWRpDzFmGHRjtqMFvRUzg==\",\n    \"X-Amzn-Trace-Id\": \"Root=1-65e6a3d9-31260eab0e97962977a6ddee\",\n    \"X-Forwarded-For\": \"XX.XXX.XX.XXX, XXX.XXX.XX.XXX\",\n    \"X-Forwarded-Port\": \"443\",\n    \"X-Forwarded-Proto\": \"https\"\n  },\n  \"multiValueHeaders\": {\n    \"Accept\": [\n      \"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7\"\n    ],\n    \"Accept-Encoding\": [\n      \"gzip, deflate, br\"\n    ],\n    \"Accept-Language\": [\n      \"ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7\"\n    ],\n    \"CloudFront-Forwarded-Proto\": [\n      \"https\"\n    ],\n    \"CloudFront-Is-Desktop-Viewer\": [\n      \"true\"\n    ],\n    \"CloudFront-Is-Mobile-Viewer\": [\n      \"false\"\n    ],\n    \"CloudFront-Is-SmartTV-Viewer\": [\n      \"false\"\n    ],\n    \"CloudFront-Is-Tablet-Viewer\": [\n      \"false\"\n    ],\n    \"CloudFront-Viewer-ASN\": [\n      \"9318\"\n    ],\n    \"CloudFront-Viewer-Country\": [\n      \"KR\"\n    ],\n    \"dnt\": [\n      \"1\"\n    ],\n    \"Host\": [\n      \"XXXXXXXXX.execute-api.us-east-1.amazonaws.com\"\n    ],\n    \"Referer\": [\n      \"https://us-east-1.console.aws.amazon.com/\"\n    ],\n    \"sec-ch-ua\": [\n      \"\\\"Not A(Brand\\\";v=\\\"99\\\", \\\"Google Chrome\\\";v=\\\"121\\\", \\\"Chromium\\\";v=\\\"121\\\"\"\n    ],\n    \"sec-ch-ua-mobile\": [\n      \"?0\"\n    ],\n    \"sec-ch-ua-platform\": [\n      \"\\\"macOS\\\"\"\n    ],\n    \"sec-fetch-dest\": [\n      \"document\"\n    ],\n    \"sec-fetch-mode\": [\n      \"navigate\"\n    ],\n    \"sec-fetch-site\": [\n      \"cross-site\"\n    ],\n    \"sec-fetch-user\": [\n      \"?1\"\n    ],\n    \"upgrade-insecure-requests\": [\n      \"1\"\n    ],\n    \"User-Agent\": [\n      \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36\"\n    ],\n    \"Via\": [\n      \"2.0 0af2958fb50cf89ab08e237abcd39288.cloudfront.net (CloudFront)\"\n    ],\n    \"X-Amz-Cf-Id\": [\n      \"XxQjwGz8_fSFSDFDFDFSDFDFSDFSDFSDRjtqMFvRUzg==\"\n    ],\n    \"X-Amzn-Trace-Id\": [\n      \"Root=1-DFSDFSD-DFDFSFDFSDFSDFD\"\n    ],\n    \"X-Forwarded-For\": [\n      \"XX.XXX.X.XX8, XXX.XX.XX.XXX\"\n    ],\n    \"X-Forwarded-Port\": [\n      \"443\"\n    ],\n    \"X-Forwarded-Proto\": [\n      \"https\"\n    ]\n  },\n  \"queryStringParameters\": null,\n  \"multiValueQueryStringParameters\": null,\n  \"pathParameters\": null,\n  \"stageVariables\": null,\n  \"requestContext\": {\n    \"resourceId\": \"hppr5vji24\",\n    \"resourcePath\": \"/\",\n    \"httpMethod\": \"GET\",\n    \"extendedRequestId\": \"UI6KAF2_IAMEZKg=\",\n    \"requestTime\": \"05/Mar/2024:04:47:21 +0000\",\n    \"path\": \"/prod/\",\n    \"accountId\": \"XXXXXXXXXXX\",\n    \"protocol\": \"HTTP/1.1\",\n    \"stage\": \"prod\",\n    \"domainPrefix\": \"DSFDFSDFSF\",\n    \"requestTimeEpoch\": 1709614041390,\n    \"requestId\": \"2cf87def-2ace-47c1-8204-XSDFFSDFSD\",\n    \"identity\": {\n      \"cognitoIdentityPoolId\": null,\n      \"accountId\": null,\n      \"cognitoIdentityId\": null,\n      \"caller\": null,\n      \"sourceIp\": \"XX.XXX.X.XX\",\n      \"principalOrgId\": null,\n      \"accessKey\": null,\n      \"cognitoAuthenticationType\": null,\n      \"cognitoAuthenticationProvider\": null,\n      \"userArn\": null,\n      \"userAgent\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36\",\n      \"user\": null\n    },\n    \"domainName\": \"XXXXXXXXX.execute-api.us-east-1.amazonaws.com\",\n    \"deploymentId\": \"0joqpi\",\n    \"apiId\": \"4hxf8if0s5\"\n  },\n  \"body\": null,\n  \"isBase64Encoded\": false\n}",
    "timestamp": "2024-03-05 04:47:23,048+0000",
    "service": "service_undefined",
    "xray_trace_id": "1-DFDFDFDF-XDFDSSFFSFSSFDFDFDS"
}

**Comment by heungh** [comment]
I found error: I found the blank with RAG API endpoint URL
